### ISSUE TITLE
Print to a Document

### ISSUE THREAD

**Issue by Shanker511** [SkylarCastator/chatgpt-terminal-extension#2]
I was wondering if you could print out to a document. Thank you

**Comment by SkylarCastator** [comment]
Sorry for the delayed reply. I was able to load all the content of previous chats into the :history location. All conversations are now saved locally to the users computer. To find out where to find this file, you can enter the ":history" and then use the ":path". You will then see all available chat histories. Also if you wish to load a previous conversation, you can use the ":load" command. I plan to add an extra save method in the future but let me know if there is anything else I can do to improve your experience!
